language: rust
os: linux
dist: xenial

rust:
  - stable
  - beta
  - nightly

cache:
  - cargo

jdk: openjdk10

script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 15 --target $JAVA_HOME
  - cargo build --verbose
  - cargo test --verbose

before_deploy:
  - cargo doc
  - mkdir public
  - cp -r target/doc public/
  - pwd
  - ls

deploy:
  strategy: git
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN  
  keep_history: false  
  local_dir: public
  on:
    branch: master
