[package]
name = "robusta"
version = "0.0.1"
authors = ["Giovanni Berti <dev.giovanniberti@gmail.com>"]
description = "Easy interop between Rust and Java"
keywords = ["ffi", "jni", "java"]
license = "MIT"
edition = "2018"
readme = "README.md"
categories = ["development-tools::ffi", "api-bindings"]
exclude = ["/robusta-codegen", "/robusta-example", "README.md"]

[dependencies]
robusta-codegen = { path = "./robusta-codegen" }
jni = "0.17.0"
paste = "1.0.0"

[workspace]
members = ["robusta-codegen", "robusta-example"]